#!/bin/bash

rsync -vart --checksum --stats --delete --progress "/Users/waliedothman/mariposa/coding/react-live-game-room/build/" -e ssh "rainwolf@development.pente.org:~/tomcat8/gameServer/live"
ssh rainwolf@development.pente.org chown -R rainwolf:tomcat8 tomcat8/
#ssh -t rainwolf@development.pente.org sudo ./restartTomcat.sh
