#!/bin/bash

rsync -vart --checksum --stats --delete --progress "/Users/waliedothman/mariposa/coding/react-live-game-room/build/" -e ssh "rainwolf@pente.org:~/tomcat/gameServer/live"
ssh rainwolf@pente.org chown -R rainwolf:tomcat8 tomcat/
#ssh -t rainwolf@development.pente.org sudo ./restartTomcat.sh
