#!/bin/bash

rsync -vart --checksum --stats --delete --progress "build/" -e ssh "rainwolf@pente.org:~/tomcat/gameServer/live"
ssh rainwolf@pente.org sudo chown -R rainwolf:tomcat tomcat/
#ssh -t rainwolf@development.pente.org sudo ./restartTomcat.sh
